//Autor:EnriqueAleman
//Institucion   :  Instituto Tecnologico de Tijuana
//Catedratico   :  Rene Solis Reyes 
//Fecha : 12/09/21
//Nombre del Ejercicio  : Makefile
//18210450
//Descripcion del problema:

condicion: condicion.o
  gcc -o condicion condicion.o
condicion.s:condicion.s
  as -o condicion.o condicion.s
clean:
  rm condicion condicion.o
